# Generated by Django 3.1.7 on 2021-04-16 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='followed_field', to=settings.AUTH_USER_MODEL),
        ),
    ]
