# Generated by Django 3.1.7 on 2021-05-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_customuser_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_post_field', to='insta.Post'),
        ),
    ]
