# Generated by Django 3.1.7 on 2021-06-08 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_customuser_saved_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_people',
            field=models.ManyToManyField(blank=True, related_name='tagging', to=settings.AUTH_USER_MODEL),
        ),
    ]
