# Generated by Django 3.1.7 on 2021-03-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_blogcomment_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='PostComment',
        ),
    ]
