# Generated by Django 3.2.5 on 2021-07-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_post_tagged_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='public_acc',
            field=models.BooleanField(default=True),
        ),
    ]
