# Generated by Django 3.2.5 on 2021-07-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_customuser_public_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='public_acc',
            new_name='is_public',
        ),
    ]
