# Generated by Django 3.1.7 on 2021-03-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20210316_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-post_date']},
        ),
    ]
