# Generated by Django 3.2.5 on 2021-07-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_customuser_pending_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_public',
            new_name='is_private',
        ),
    ]
