# Generated by Django 3.2.5 on 2021-07-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_rename_is_public_customuser_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
