# Generated by Django 3.2.5 on 2021-08-06 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_alter_customuser_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_field', to=settings.AUTH_USER_MODEL),
        ),
    ]
