# Generated by Django 3.2.5 on 2021-08-22 16:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0017_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'base_manager_name': 'active_stories', 'ordering': ['created_at']},
        ),
        migrations.AlterModelManagers(
            name='story',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('active_stories', django.db.models.manager.Manager()),
            ],
        ),
    ]
