# Generated by Django 3.2.5 on 2021-08-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0019_auto_20210822_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['created_at']},
        ),
    ]
