# Generated by Django 3.2.5 on 2021-11-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0020_alter_story_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='childcomments',
            field=models.ManyToManyField(blank=True, related_name='childcomment', to='insta.PostComment'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='is_parentcomment',
            field=models.BooleanField(default=True),
        ),
    ]
