# Generated by Django 3.2.5 on 2021-11-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0021_auto_20211102_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='childcomments',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='is_parentcomment',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='insta.postcomment'),
        ),
    ]
