# Generated by Django 3.2.5 on 2021-12-27 19:31

from django.db import migrations, models
import insta.validators


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0024_alter_postcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(upload_to='images_post', validators=[insta.validators.validate_file_extension]),
        ),
    ]
