# Generated by Django 3.2.5 on 2022-01-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0025_alter_post_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
