# Generated by Django 3.2.5 on 2022-01-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0026_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='hashtag_posts', to='insta.Post'),
        ),
    ]
